### ISSUE TITLE
How to get [Backup Directory Path]

### ISSUE THREAD

**Issue by David-Maisonave** [stg-annon/stashapi#12]
How can I get the **Backup Directory Path**. This is the field in System->[Application Paths]->[Backup Directory Path].

I'm trying to implement logic to limit the number of backups.

Side-Note: I'm not sure yet when to post a question in CommunityScripts or when to post it in [stg-annon->stashapi](https://github.com/stg-annon/stashapi/issues). It would help if when posting a question, the issue template would state what type of issues should be posted.
There doesn't seem to be as much eyes in stg-annon->stashapi compared to CommunityScripts, which makes me think my question would get answered faster in CommunityScripts.

**Comment by stg-annon** [comment]
it would be part of a configuration query so for stashapi that would be

```py
stashapp.get_configuration("general { backupDirectoryPath }")
```

It probably would be answered quicker in the community repo or in Discord stashapi is just a python wrapper around the GraphQL API that stash provides it is intended to mirror most of the functions of the API to make it easier to develop python integrations, this specific question as more to do with Stash's API

More generally if your looking to replicate something from the UI take a look in the network section of the browser dev tools and you will see what call the UI is making to the API

**Comment by David-Maisonave** [comment]
> stashapp.get_configuration("general { backupDirectoryPath }")

Thank you very much.
Can it safely be called like this `stashapp.get_configuration()['general']['backupDirectoryPath']` instead? Or could that cause issues?

> More generally if your looking to replicate something from the UI take a look in the network section of the browser dev tools and you will see what call the UI is making to the API

I'm not sure what you mean by **browser dev tools**. Are you referring to the GO files in the following path:
`stash\stash-0.26.2\internal\api`

I've been looking for documentation on stashapi, but I can't seem to find any.
I was expecting to see something in [docs.stashapp.cc](https://docs.stashapp.cc/in-app-manual/plugins/), but I found nothing that came close to covering it.

Is there some place else I should look for documentation?

Thank you for all your help.

**Comment by stg-annon** [comment]
> Can it safely be called like this `stashapp.get_configuration()['general']['backupDirectoryPath']` instead? Or could that cause issues?

I believe it is safe to do this unless there is an error encountered somewhere in the request to stash, if that happens you'll get a KeyError

By browser dev tools I mean the F12/"Inspect Element" portion of your browser, when interacting with the Stash application you can see the requests the UI is making to the Go backend

Stash the application is self documenting see `http://localhost:9999/playground` 

stashapp-tools generally trys to follow the same structure just in a more pythonic syntax, all of the available documentation for stashapp-tools are in the form of docstrings which will show up when using an IDE like VS Code

**Comment by David-Maisonave** [comment]
> By browser dev tools I mean the F12/"Inspect Element" portion of your browser, when interacting with the Stash application you can see the requests the UI is making to the Go backend

I just tried this on both Firefox and Chrome.  I wanted to see if I can find what's sent to the backend  when clicking [**Clean generated files...**] in the Task->Maintenance option. But I didn't see any indication of that. I did try inspecting the sub sections, but there's so many sub parts, that it's like finding a needle in a hey stack.
Here's snapshots before and after clicking the button with F12/Inspect displayed using Chrome.
![F12_InspectElement_CleanGeneratedFiles](https://github.com/user-attachments/assets/665daaf5-aa9c-4eba-a8ef-863756ee68d8)

After clicking the button.
![F12_InspectElement_CleanGeneratedFiles_AfterClickingButton](https://github.com/user-attachments/assets/4b7da93b-91bd-4ab4-a5f7-64c1f6f32c3c)

I guess this might be more obvious to someone more familiar with GraphiQL and/or using the F12-Inspect.

Can you please direct me as to specifically what section I should be looking for?
Thank you

**Comment by stg-annon** [comment]
at the top of the window you will see a tab called `Network` select that tab and you will see the request being made

**Comment by David-Maisonave** [comment]
> at the top of the window you will see a tab called Network select that tab and you will see the request being made

Thank you so much. That does clarify things for me now.
And thank you for being so patient with me. ☺️ I appreciate it.

With the tools you've shown me I was able to figure out how to implement the metadata_clean_generated.
``` python
def metadata_clean_generated(self, blobFiles=True, dryRun=False, imageThumbnails=True, markers=True, screenshots=True, sprites=True, transcodes=True):
    query = """
    mutation MetadataCleanGenerated($input: CleanGeneratedInput!) {
      metadataCleanGenerated(input: $input)
    }
    """
    clean_metadata_input = {
        "blobFiles": blobFiles,
        "dryRun": dryRun,
        "imageThumbnails": imageThumbnails,
        "markers": markers,
        "screenshots": screenshots,
        "sprites": sprites,
        "transcodes": transcodes,
    }
    result = self.call_GQL(query, {"input": clean_metadata_input})
    return result
```

The above variables are in the following network graphql listing:
![Network_Graphql_MetadataCleanGenerated](https://github.com/user-attachments/assets/b34e4b30-02ce-49e7-a6dc-efdc99640e4e)

However, when I look at the network graphql listing for MetadataClean, I only see the dryRun variable:
![Network_Graphql_MetadataClean](https://github.com/user-attachments/assets/7434fc56-dcbb-4f92-92d3-eba57c502a2a)

The metadata_clean function has a paths variable in addition to the dryRun variable. At first I was wondering how would you know to include the paths variable, but when I removed the paths variable from the input, the function still worked.
When I add the same variable to metadata_clean_generated, that fails with an error indicating the paths variable shouldn't be there.

So my conclusion is that the **paths** variable seems to be an undocumented supported variable for **MetadataClean**.

Is that correct?

**Comment by stg-annon** [comment]
The network tab is a good place to see a working example of something you might want to do but further documentation of a function can be found in the playground

> So my conclusion is that the **paths** variable seems to be an undocumented supported variable for **MetadataClean**.

not undocumented but unused in that call from the UI, see `CleanMetadataInput` in the playground for what the `metadataClean` function is expecting as the input

**Comment by David-Maisonave** [comment]
Thank you again for all your help.
