### ISSUE TITLE
Log message length overflowing golang buf in special cases

### ISSUE THREAD

**Issue by ArchitektApx** [stg-annon/stashapi#18]
### The Problem
The discord has several mentions of users having multiple plugins like timestamp.trade throw with "error 120" in some cases, especially with timestamp.trades "create movie" option enabled. 

### The Issue
"error 120" and the immediate throw hints to a log message that overflows the golang buf i.e larger than what is defined by `LOG_PAYLOAD_MAX_SZ` at https://github.com/stg-annon/stashapi/blob/9e2e4a673f35a6e30b89c923c6857a9a0b6d7133/log.py#L38C1-L38C19

The truncation expects all characters to be of the same byte length, which is not true, especially for non-latin utf8 stuff and emojis and other encodings for example.
This is causing issues with max-length or close to max-length log output when it contains said characters.

### Example
For example creating a new movie/scene/marker where the data is close to or above 64k characters and contains some special characters results in termination with exit code 120. Especially with user generated content like timestamp.trade, this can happen quite often and cannot always be handled by the plugin itself, because public methods of stashapp-tools themselves generate log-messages based on the requests data like update_scene. 

A quick-and-dirty fix is to set to set `LOG_PAYLOAD_MAX_SZ` to something smaller like 64000 exactly to give some "wiggle-room" for larger-byte-length chars.

**Comment by stg-annon** [comment]
resolved with e133a96a30d294b1ce1efd10be75c60cb77466ed
