### ISSUE TITLE
find_scene_markers is missing filter argument which GraphQL API supports

### ISSUE THREAD

**Issue by MinasukiHikimuna** [stg-annon/stashapi#20]
https://github.com/stg-annon/stashapi/blob/52aba25e6fea17cc0eb0ea58545f5e540431f630/stashapp.py#L1748

This only supports scene_marker_filter and fragment. As filter is missing, one cannot influence page or per_page which essentially means that only the first page of scene markers can be read.

Stashapp's GraphQL API does support filter argument.

**Comment by stg-annon** [comment]
hmm yeah that's an oversight fe043fa resolves this
