### ISSUE TITLE
find_performer crashing on large loads

### ISSUE THREAD

**Issue by scruffynerf** [stg-annon/stashapi#7]
ran into this while writing code to avoid existing performers being created as tags (coming soon)

Within `find_performer`
```
if len(performer_matches) > 1:
			warn_msg = f"Matched multiple Performers to '{performer['name']}'"
			if on_multiple == OnMultipleMatch.RETURN_NONE:
				self.log.warning(f"{warn_msg} returning None")
				return None
			if on_multiple == OnMultipleMatch.RETURN_LIST:
				self.log.warning(f"{warn_msg} returning all matches")
				return [self.find_performer(p["id"]) for p in performer_matches]
			if on_multiple == OnMultipleMatch.RETURN_FIRST:
				self.log.warning(f"{warn_msg} returning first match")
		if len(performer_matches) > 0:
			return self.find_performer(performer_matches[0]["id"])
```

if the performer found has too much info to load (in my found issue: Scenes: 205, Movies: 137, Appears With: 945)
which the stock fragment tries to do... python crashes out with a error 120  (Python 3.11, and working fine otherwise)
and never continues onward to let me look at the results

Fragment value is passed in to the original find_performer, but the above don't inherit it, leading to the stock fragment problem.
I quick-solved by adding `, create, fragment` to the 2 find_performer calls (returning a list or the first) above, and using a fragment in the original call like 'id name'  which bypassed the loading problem, and solved the crashing.

**Comment by stg-annon** [comment]
https://github.com/stg-annon/stashapi/commit/80b2bb29fa493fce70748ec3699d8ac2f93e38b6 should fix it create should not be necessary in this context as it already found a performer with an ID by this point so it will never need to create them

**Comment by scruffynerf** [comment]
unsure it's the loading, maybe it's a recursive issue?  (the invoking of the id in that manner?)  Either way, it solves it.
